added async func time execution util
brightsource-il/Bsii.Dotnet.Utils pull request #22
Opened 2021-06-28 11:24 UTC by dperetz1

2021-06-28 11:25 UTC, dperetz1 commented
@eitanhs , @brightsource-il/fresco  - I can't add reviewers  (it's a fork , I got no permissions to push a branch), please take a look

2021-06-28 11:27 UTC, kpahima requested changes

2021-06-28 11:27 UTC, kpahima commented on Bsii.Dotnet.Utils/AsyncUtils.cs
> +        public static async Task<(T res, TimeSpan elapsed)> TimeExecutionAsync<T>(this Func<Task<T>> action)
Please add the SFC synch functions as well so SFC can use this Nuget as well

2021-06-28 11:39 UTC, dperetz1 commented on Bsii.Dotnet.Utils/AsyncUtils.cs
> +        public static async Task<(T res, TimeSpan elapsed)> TimeExecutionAsync<T>(this Func<Task<T>> action)
done

2021-06-28 11:41 UTC, kpahima submitted a review, later dismissed

2021-06-28 16:08 UTC, eitanhs reviewed
Thanks!
Please add unit tests...

2021-07-04 12:55 UTC, dperetz1 commented
added unit tests

2021-07-07 16:01 UTC, dperetz1 commented
@eitanhs ping

2021-07-11 19:35 UTC, eitanhs approved these changes

2021-07-11 19:39 UTC, eitanhs approved these changes

2021-07-11 19:54 UTC, merged